=== Masterkros2003/Lenguajes-2024_Carlos_Hurtado/segundo_trimestre/tema_10_xml/ejercicio12/ej12.dtd
<!ELEMENT reservas (vuelo+)>
<!ELEMENT vuelo (codigo, aerolinea, origen, destino, fecha, horaSalida, horaLlegada, pasajeros)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT aerolinea (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horaSalida (#PCDATA)>
<!ELEMENT horaLlegada (#PCDATA)>
<!ELEMENT pasajeros (pasajero+)>
<!ELEMENT pasajero (nombre, dni, asiento, clase)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT asiento (#PCDATA)>
<!ELEMENT clase (#PCDATA)>

=== Masterkros2003/Lenguajes-2024_Carlos_Hurtado/segundo_trimestre/tema_10_xml/ejercicio12/ej12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reservas SYSTEM "ej12.dtd">

<reservas>
    <vuelo>

        <codigo>IB-1234</codigo>
        <aerolinea>Iberia</aerolinea>
        <origen>Madrid</origen>
        <destino>Barcelona</destino>
        <fecha>01-01-2025</fecha>
        <horaSalida>08:00</horaSalida>
        <horaLlegada>09:45</horaLlegada>

        <pasajeros>

            <pasajero>
                <nombre>Carlos Hurtado</nombre>
                <dni>12345678-A</dni>
                <asiento>12-A</asiento>
                <clase>Turista</clase>
            </pasajero>

            <pasajero>
                <nombre>Jesus Panadero</nombre>
                <dni>87654321-B</dni>
                <asiento>12-B</asiento>
                <clase>Turista</clase>
            </pasajero>

        </pasajeros>

    </vuelo>
</reservas>
